#!/bin/bash

. /etc/breakteam/scripts.conf

printf "=========================================================================\n"
printf "                            Change Port Admin\n"
printf "=========================================================================\n"
printf "Current Port: $admin_port                                              \n\n"
read -r -p "You want change ? [y/N] " response
case $response in [yY][eE][sS]|[yY])
	echo -n "Enter port [ENTER]: "
	read new_admin_port
	if [ "$new_admin_port" == "" ] || [ $new_admin_port == "7777" ] || [ $new_admin_port -lt 2000 ] || [ $new_admin_port -gt 9999 ] || [ $(lsof -i -P | grep ":$new_admin_port " | wc -l) != "0" ] || [ "$new_admin_port" == "$admin_port" ]; then
		echo "Port admin is invalid. Exit."
		exit
	fi

	sed -i "s/listen $admin_port;/listen $new_admin_port;/g" /etc/nginx/conf.d/$server_name.conf
	sed -i "s/port=$admin_port/port=$new_admin_port/g" /etc/fail2ban/jail.local
	sed -i "s/admin_port=\"$admin_port\"/admin_port=\"$new_admin_port\"/g" /etc/breakteam/scripts.conf

	if [ -f /root/breakteam.txt ]; then
		sed -i "s/:$admin_port\//:$new_admin_port\//g" /root/breakteam.txt
	fi

	# Open port
	iptables -D INPUT -p tcp --dport $admin_port -j ACCEPT
	iptables -I INPUT -p tcp --dport $new_admin_port -j ACCEPT
	iptables-save > /dev/null

	nginx -s reload

	echo "New Port: $new_admin_port "
        ;;
    *)
        echo "Exit."
        ;;
esac
exit
